name: Trigger auto deployment for makoni-ai-frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/makoni-ai-frontend-AutoDeployTrigger-58fd8671-850a-4c48-b069-ab6eed60593a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MAKONIAIFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MAKONIAIFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MAKONIAIFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: makoniairegistry.azurecr.io
          registryUsername: ${{ secrets.MAKONIAIFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MAKONIAIFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: makoni-ai-frontend
          resourceGroup: makoni-ai-rg
          imageToBuild: makoniairegistry.azurecr.io/makoni-ai-frontend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


